spring:
  application:
    name: blog-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          lob:
            non_contextual_creation: true
          type:
            binary: byte[]
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com.example.backend: TRACE
    org:
      hibernate:
        SQL: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%level] %c{1.} [%t] %msg%n"
    file: "%d{HH:mm:ss.SSS} [%level] %c{1.} [%t] %msg%n"

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver


server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
