spring:
  mail:
    host: smtp.test.com
    port: 587
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    root: INFO

mail:
  to: test@example.com