spring:
  application:
    name: blog-service
  config:
    import: classpath:sensitive_data.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8080

