spring:
  datasource:
    url: ${{ secret.DB_URL }}
    username: ${{ secret.DB_USER }}
    password: ${{ secret.DB_PW }}
    driver-class-name: org.postgresql.Driver

server:
  port: 5000

logging:
  level:
    org.springframework.boot.web: DEBUG