spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver

server:
  port: 5000

logging:
  level:
    org.springframework.boot.web: DEBUG